AGENT = [
            'Mozilla/5.0 (compatible; Arachni/1.5.1; Linux x86_64)',
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Betabot/2.0',
            'Mozilla/5.0 (compatible; Bewica-Security-Scan/1.0; +https://bewica.com)',
            'Mozilla/5.0 (BFAC/1.4; compatible; Linux x86_64)',
            'Mozilla/5.0 (compatible; CommixScanner/0.3; +https://github.com/commixproject/commix)',
            'Mozilla/5.0 (DetectifyBot/1.0; +https://detectify.com)',
            'Mozilla/5.0 (DirBuster/1.0; compatible; Java/1.8.0_231)',
            'Mozilla/5.0 (FimapScanner/1.0; compatible; Linux)',
            'Mozilla/5.0 (FFUF/1.3.0; fuzz faster)',
            'Mozilla/5.0 (Gobuster/3.0; Go-http-client/1.1)',
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Havij/1.17',
            'Mozilla/5.0 (compatible; HexometerBot/1.0; +https://hexometer.com)',
            'Mozilla/5.0 (JBroFuzz/2.5; Java/1.8.0)',
            'Mozilla/5.0 (compatible; JorgeeScanner/1.0)',
            'Mozilla/5.0 (libwhisker/2.1; Perl)',
            'Mozilla/5.0 (compatible; masscan/1.3.2; +https://github.com/robertdavidgraham/masscan)',
            'Mozilla/5.0 (MorfeusScanner/1.0; compatible; Linux)',
            'Mozlila/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
            'Mozilla/5.0 (Nessus/8.13; Windows NT 10.0)',
            'Mozilla/5.0 (compatible; Netlab360Scanner/1.0)',
            'Mozilla/5.0 (compatible; Netsparker/1.0; +https://netsparker.com)',
            'Mozilla/5.0 (Nikto/2.1.6; Linux x86_64)',
            'Mozilla/5.0 (compatible; nmap script; +https://nmap.org)',
            'Mozilla/5.0 (Nuclei/v2.5.3; +https://projectdiscovery.io)',
            'Mozilla/5.0 (compatible; OpenVAS/9.0; Linux)',
            'Mozilla/5.0 (compatible; SiteLockSpider/1.0; +http://www.sitelock.com)',
            'Mozilla/5.0 (sqlmap/1.4.12.23#dev; Python 3.7.2)',
            'Mozilla/5.0 (compatible; SysScanBot/1.0; +https://cyber.nj.gov)',
            'Mozilla/5.0 (TsunamiSecurityScanner/1.0; +https://github.com/google/tsunami-security-scanner)',
            'Mozilla/5.0 (W3af.org/1.6; Python 3.8)',
            'Mozilla/5.0 (compatible; WebBandit/1.0; +http://www.robotstxt.org/db/webbandit.html)',
            'Mozilla/5.0 (WebShag/1.10; Java/1.7.0)',
            'Mozilla/5.0 (WFuzz/3.0; Python 3.9)',
            'Mozilla/5.0 (compatible; WhatWeb/0.5.5; +https://www.morningstarsecurity.com/research/whatweb)',
            'Mozilla/5.0 (compatible; WPRecon/1.1; +https://github.com/blackploit/wprecon)',
            'Mozilla/5.0 (wpscan/3.8.17; Ruby 2.7.0)',
            'Mozilla/5.0 (zgrab/0.1; Go-http-client/1.1)',
            'Mozilla/5.0 (ZmeuScanner/1.0; compatible)'
        ]